```{r setup}
# load required libraries
library(dplyr)
library(ggplot2)
library(xml2)
library(stringr)
library(purrr)

# declare keyboard system layout
system = "C" # either "C" or "B"

# load in button layout reference
df_buttons = read.csv("reference/all_buttons.csv") |> 
  tidyr::replace_na(replace = list(accidental = "")) |> 
  mutate(note = paste0(letter, accidental),
         .keep = "unused") |> 
  # hide the buttons that are not really needed
  filter_out(note %in% c("B#", "Cb", "E#", "Fb")) 

# rearrange buttons if system is "B"
if(system == "B") {
  
  # do initial rearranging of row order
  df_buttons = df_buttons |> 
    filter_out(row == 4) |> 
    mutate(row = case_when(
      row == 1 ~ 3,
      row == 3 ~ 1,
      TRUE ~ row))
  
  # duplicate rows 1 and 4
  df_row_to_copy = df_buttons |> 
    filter(row == 1) |> 
    mutate(row = 4)
  
  # adjust column positions to position two rows correctly
  df_buttons = bind_rows(df_buttons,
                         df_row_to_copy) |> 
    mutate(col = case_when(
      row == 4 ~ col - 0.5,
      row == 5 ~ col - 1,
      TRUE ~ col,
    ))
  
}

# list names of available musicxml file tunes, in the folder called musicxml
available_musicxml = list.files(path = "musicxml") |> 
  stringr::str_remove(pattern = "\\.musicxml")
```

```{r process selected tune}

# select the tune to chart, by changing the [1] to another number
music_xml = available_musicxml[1]

# load in musicxml file
xml_data = xml2::read_xml(x = paste0("musicxml/",
                                     music_xml,
                                     ".musicxml"))

# extract notes from musicxml tune
df_notes = xml2::xml_find_all(x = xml_data, 
                              xpath = ".//pitch") |> 
  xml2::xml_text() |> 
  as.data.frame(nm = "xml_pitch") |> 
  mutate(note = stringr::str_sub(string = xml_pitch,
                                 start = 1,
                                 end = -2),
         # identify all of the flat notes
         note = stringr::str_replace(string = note,
                                     pattern = "-1",
                                     replacement = "b"),
         # identify all of the sharp notes
         note = stringr::str_replace(string = note,
                                     pattern = "1",
                                     replacement = "#"),
         # identify which octave the note is from
         octave = as.numeric(stringr::str_extract(string = xml_pitch,
                                                  pattern = "\\d{1}$")))
# specify which rows to use for chart display
rows_to_use = c(1:5)

# match tune's notes to the buttons
df_tune = left_join(x = df_notes,
                    y = df_buttons |> 
                      filter(row %in% rows_to_use),
                    by = join_by(octave, note),
                    relationship = "many-to-many")

# options for which rows to use when calculating distance traveled
row_triplets = list(1:3, 2:4, 3:5)

# calculate distance traveled using only certain triplets of rows
distance_text = purrr::map(
  .x = c(1:3),
  .f = ~ paste0(
    "Rows ",
    paste(row_triplets[[.x]], collapse = "+"),
    " travels ",
    janitor::round_half_up(
      x = df_tune |> 
        filter(row %in% row_triplets[[.x]]) |> 
        # calculate pythagorean distance between consecutive notes buttons
        mutate(distance = sqrt((row - dplyr::lag(row))^2 + (col - dplyr::lag(col))^2)) |> 
        pull(distance) |> 
        sum(na.rm = TRUE),
      digits = 1),
    " units")) |> 
  unlist() |> 
  paste0(collapse = "\n")

# create chart
ggplot() +
  scale_y_continuous(limits = c(1, 18)) +
  scale_x_reverse(limits = c(0, 6),
                  breaks = c(1:5)) +
  # highlight buttons used in tune
  geom_point(data = df_tune,
             mapping = aes(x = row,
                           y = col),
             alpha = 0.1,
             shape = 21,
             size = 9,
             fill = "red",
             colour = "red") +
  # create background of button board
  geom_point(data = df_buttons,
             mapping = aes(x = row,
                           y = col,
                           fill = colour),
             shape = 21,
             size = 7) +
  # add the text labels to the buttons
  geom_text(data = df_buttons |> group_by(octave,
                                          row,
                                          col,
                                          colour) |>
              summarise(note = paste(note, collapse = "\n"),
                        .groups = "drop"),
            mapping = aes(x = row,
                          y = col,
                          label = note,
                          colour = colour),
            size = 2) +
  # put opposite colour text on the corresponding button colour
  scale_colour_manual(values = c("black" = "white", "white" = "black"),
                      guide = "none") +
  scale_fill_identity() +
  labs(title = paste0(music_xml,
                      " (",
                      system,
                      ")"),
       caption = distance_text) +
  theme_void() +
  theme(axis.title.x = element_text(),
        axis.text.x = element_text(),
        plot.title = element_text(hjust = 0.5),
        plot.caption.position = "panel",
        plot.caption = element_text(hjust = 0.5))

# save chart in folder called 'charts'
ggsave(filename = paste0("charts/",
                         paste0(music_xml,
                                " (",
                                system,
                                " system)"),
                         ".png"),
       width = 5,
       height = 16,
       units = "cm")

```

